[profile.default]
src = "src"
test = "test"
script = "script"
out = "out"
libs = ["lib"]
solc_version = "0.8.24"
evm_version = "paris"
optimizer = true
optimizer_runs = 200

remappings = [
  "openzeppelin-contracts/=lib/openzeppelin-contracts/"
]
